# -*- coding: utf-8 -*-
"""Unemployment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tLuCt2DBek3UcmK-Vethbfj2DM8IpvTb
"""

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

data = pd.read_csv('Unemployment_Rate.csv')

print(data.head())

print(data.isnull().sum())

data.columns= ["States","Date","Frequency",
               "Estimated Unemployment Rate","Estimated Employed",
               "Estimated Labour Participation Rate","Region",
               "longitude","latitude"]

plt.title("UNEMPLOYMENTS IN INDIA")
sns.histplot(x="Estimated Employed", hue="Region", data=data)
plt.show()

plt.figure(figsize=(12, 10))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate", hue="Region", data=data)
plt.show()

corr_matrix = data.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

import plotly.express as px

unemploment = data[["States", "Region", "Estimated Unemployment Rate"]]
plot = px.sunburst(unemploment, path=["Region", "States"],
                     values="Estimated Unemployment Rate",
                     width=800, height=800, color_continuous_scale="RYd1GR",
                     title="Unemployment Rate in India")
plot.show()